### ISSUE TITLE
Evaluate some more utility functions

### ISSUE THREAD

**Issue by azakus** [Polymer/dom5#27]
[there](https://github.com/PolymerLabs/polymer-css-build/pull/1#discussion_r66338522) [are](https://github.com/PolymerLabs/polymer-css-build/pull/1#discussion_r66338583) [a lot](https://github.com/PolymerLabs/polymer-css-build/pull/1#discussion_r66338626) of simple utilities that could move over :)

**Comment by TimvdLippe** [comment]
It seems that the referenced links to not show the corresponding comment. Could you copy the content of the comments into the issue description?

**Comment by usergenic** [comment]
closing this issue.  lets file another one when we can know what the utility functions.
