### ISSUE TITLE
npm install dom5 return 404 error

### ISSUE THREAD

**Issue by casper1314** [Polymer/dom5#38]
Hi, 

I ran "npm install dom5" today but returned below errors. Do you know how to solve it? Thank you very much.

npm WARN package.json rjs-build-analysis@0.0.3 No repository field.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/parse5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'dom5'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 2.6.39-400.215.2.el6uek.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "dom5"
npm ERR! cwd /predix/Documents/PredixApps/my_projects_2/predix-rmd-ref-app/rmd-ref-app-ui
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

**Comment by thecodejack** [comment]
were you able to resolve it? I am getting same error as well

**Comment by rictic** [comment]
Hm, I notice that you're seeing `types/parse5` rather than the correct `@types/parse5`.

What version of `npm` are you using?

**Comment by thecodejack** [comment]
I am using v3.10.8. I found a workaround. Looks like my private npm registry was throwing this error. So I have added following line in `.npmrc` file.

```
@types:registry=https://registry.npmjs.com
```

**Comment by justinfagnani** [comment]
Is this still occurring without the workaround? We're not doing anything special in dom5 that should be tripping npm up.

**Comment by TimvdLippe** [comment]
Closing this issue due to its age and I am able to install this package just fine with `npm@5.0.3`. This was probably an artifact of an outdated version of `npm`.
