### ISSUE TITLE
Move @types dependencies to devDependencies

### ISSUE THREAD

**Issue by freshp86** [Polymer/dom5#45]
Do the following deps need to be in the "dependencies" section of package.json? Can they be moved to "devDependencies" instead?

```
"@types/clone": "^0.1.29",
"@types/node": "^4.0.30",
"@types/parse5": "^2.2.32"
```

This will reduce the code being downloaded when someone depends on dom5.

**Comment by freshp86** [comment]
cc @danbeam

**Comment by danbeam** [comment]
@tjsavage

**Comment by tjsavage** [comment]
Seems like they'd be ok to move to me - @justinfagnani WDYT?

**Comment by rictic** [comment]
The reasoning here is that these typings are necessary to understand the types that this module produces. That's not really useful for a non-typescript client of course. If this is about keeping size down for the Chrome checkin of node tools, my recommendation would be a post-install step that deletes the `node_modules/@types` directory, as other node modules will have this sort of dependency too.

**Comment by justinfagnani** [comment]
We purposefully keep `@types` dependencies with their respective modules - either in dependencies or devDependencies. For good rationale, this is discussed here: https://github.com/Microsoft/types-publisher/issues/81

@rictic's suggestion is good. You can nuke the whole `node_modules/@types/` directory with no problems.

**Comment by danbeam** [comment]
@justinfagnani right, we're just asking to move to devDependencies.

I don't think it makes a ton of sense to download these just to delete them.  We also have a filter that's deleting things and it's hard to know what's required.  Some of @freshp86's attempts to remove things after `npm install` have broken stuff in subtle ways.

basically: I don't see why this stuff would be desired as a result of `npm install --production`, which is what we're doing.

**Comment by rictic** [comment]
If we moved them to devDependencies then typescript users of this package would not be able to consume the typings produced by this module without either installing the dom5's devDependencies (which npm doesn't really support) or adding the typings to their own dependencies, which is fragile.

Deleting things from `@types` is safe, it only contains typescript type info. It's an npm scope that's maintained by the typescript team for this purpose. Unless you care about typescript type info you can always delete `node_modules/@types`.

**Comment by justinfagnani** [comment]
We need them in `dependencies` so that their installed into packages that depend on `dom5` as a regular dependency.

**Comment by justinfagnani** [comment]
Just to be clear, this change would break our other libraries that use `dom5`.

**Comment by danbeam** [comment]
in apt-get, there are separate header or dev packages for those that need symbols or types.  why does something like that not work for this case?

**Comment by justinfagnani** [comment]
I guess cause it doesn't exist. npm only installs what's in `dependencies`.

**Comment by rictic** [comment]
We could create another npm package – `dom5-types` – that has all of dom5's `@type` dependencies, and require all typescript users of dom5 depend on it. I believe that would work.

I believe that other libraries you depend on are likely to use typescript, either now or in the future. Deleting `node_modules/@types` is safe and doesn't require changing the conventions of the ecosystem.

I think it has a better time cost/reward ratio, as we'd need to make `-types` repos for all of our tools repos, and most of the benefit would be wiped away the first time any of your transitive dependencies was written in typescript that the Polymer tools team didn't author.

**Comment by justinfagnani** [comment]
@rictic I think that would be far too cumbersome on us. We'd have to maintain a separate `-types` package for each of ours, add it as a devDependency, and keep them in sync - each dependency in a package would need a corresponding @types or `-types` dependency. Local development would be a pain, we the two packages would have to be published in sync together to avoid breaking all downstream dependents.

**Comment by freshp86** [comment]
To be fair, packages pulled via NPM are full of unnecessary bytes, and addressing this bug would not greatly improve the overall picture. I filed this as a small step towards reducing the dependencies that will be pulled down by Chromium, once the toolchain starts using Node. Here are some numbers

```
mkdir temp;
cd temp;
# Pull down the 4 direct dependencies Chromium will have.
npm install --no-bin-links --only=prod vulcanize crisper polymer-css-build uglifyjs
du -h node_modules | tail -n1 | cut -f1
#Prints 25MB

rsync -c --delete -r -q --exclude-from="rsync_exclude.txt" \
    --prune-empty-dirs "node_modules/" "node_modules_filtered/"
du -h node_modules_filtered | tail -n1 | cut -f1
#Prints 19MB

tar cfz node_modules.tar.gz node_modules_filtered
du -h node_modules.tar.gz | tail -n1 | cut -f1
#Prints 3MB
```
Where the contents of rsync_exclude.txt are
```
*/.*
*/example/
*/examples/
*/jsdoc2md/
*.md
*.png
*.sh
*.svg
*/test/
*/@types/
*.yml
```

I don't know what an ideal solution would be, but for now post-download filtering seems more feasible than chasing every transitive dependency author of our 4 direct dependencies to more aggressively filter their published bytes (except for some cases where there is a significant size benefit like using nopt instead of command-line-args package).

**Comment by rictic** [comment]
I expect you could add `.ts` to that list as well.

**Comment by rictic** [comment]
Installing those packages locally, I see 25MB, ~20MB of which is taken up by four separate copies of core-js v2.4.1?

Hm, that can't be right though, as `yarn add vulcanize crisper polymer-css-build uglifyjs` only installs one version of core-js, but still takes up 23MB? That's very strange.

I suspect that you can shave 4.7MB off the disk by removing `node_modules/hydrolysis/hydrolysis.js` as it's a browserified bundle that's unused by node code.

Another 1MB is in fonts shipped with the command-line-args library at `node_modules/command-line-args/out/command-line-args/2.1.4/fonts`

The rest seems fairly long-tail. Many libraries are publishing both src and dist directories, but it's hard to tell which is desirable, as sometimes the src is just there for source maps and dist is all you want, but other times dist is for the browser and src is all that's used for node.

**Comment by muj-beg** [comment]
The issue we're running into are type conflicts when running our webpack based builds that include this lib.  For example, since our project uses webpack, we import the type definitions  for wepack-env, instead of node.  However, since both wepack-env.d.ts and node.d.ts declare some of the same names (ex. `require`), we get errors when compiling.

I would think this would also be an issue when a different version of a dependent library is needed by the app.  Say, for example, our app needs to use type definitions for Parse5@3.0.1.  Since dom5 already includes a type-def for this library in it's distribution, this would cause TypeScript  duplicate identifier errors.

**Comment by rictic** [comment]
I believe that typescript handles type conflicts at the module level correctly. If you depend on A which depends on `@types/B@1.0.0` and C which depends on `@types/B@2.0.0`, I believe typescript handles that correctly, and the type defs for A see 1.0.0, and C sees 2.0.0.

It's trickier with globals like `node.d.ts` and `webpack-env.d.ts`, I'm not sure what the solution is there, but it seems like it needs to happen at the typescript level, rather than at the individual project level. I'd recommend filing a bug on Microsoft/typescript.

**Comment by usergenic** [comment]
FWIW I moved `@types/clone` to devDependencies and now `@types/parse5` is the only remaining non-devDependencies entry.

**Comment by usergenic** [comment]
I'm going to close this issue as it is presently non-actionable as long as there all exposed types are actually part of the public interface of dom5, since that is intended.
